---
all:
  hosts:
    node-1:
      ansible_host: 10.100.1.10
      vm_id: 1
      role: controlplane
      ansible_user: debian
    #node-2:
    #  ansible_host: 10.100.1.20
    #  vm_id: 2
    #  role: controlplane
    #  ansible_user: debian
    #node-3:
    #  ansible_host: 10.100.1.30
    #  vm_id: 3
    #  role: worker
    #  ansible_user: debian
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
